#spring:
  #profiles:
    #active: true
dubbo:
  scan:
    base-packages: zoua.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://127.0.0.1
  #application:
    #qos-enable: true
  cloud:
    subscribed-services: nacos-dubbo-provider
  #consumer:
    #check: false 
  #provider:
    #loadbalance: roundrobin
    
