server:
  port: 8902
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: service-feign
   
 #换成httpclient访问方式
 feign:
   httpclient:
     enabled: true
     