server:
  port: 7000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          # 开启网关对注册中心的支持
          enabled: true
      routes:
        - id: order_server
          # lb是设置从注册中心按服务名称获取服务信息，并遵循负载均衡策略
          uri: lb://order-server
          predicates:
            - Path=/order/**
            # 设置自定义的断言
            - Sex=0
            - Time=6,0,23,0