server:
  port: 8588
spring:
  application:
    name: Seata-Consumer
#指定nacos server地址
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
#数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.1:3306/seata_consumer?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: my_test_tx_group
  config:
    type: nacos
    nacos:
      namespace:
      serverAddr: 127.0.0.1:8848
      group: SEATA_GROUP
 
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      namespace: