server:
  port: 8300


#####################################################################################################
# 配置服务客户端Client应用入口（正常测试 ConfigClient ）
# profile: profile-dev
#####################################################################################################





#####################################################################################################
# 配置服务客户端Client应用入口（链接 ClientServer 测试，同时本地也有一份配置文件，那么该如何抉择呢？）
# profile: profile-local-dev
#####################################################################################################















